server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tKP7BEWXrMjnyXkstqG
      secret-key: WNUDeEfg2NpOKbAfG2rabdcFRtc9P4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucketName: youyu-mall
  application:
    name: gulimall-third-party